import './output.css';
import { Inter as FontSans } from 'next/font/google';
import { cn } from 'libs/shared/src/utils';

export const metadata = {
  title: 'Welcome to pb-next',
  description: 'Generated by create-nx-workspace',
};

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <div className="bg-slate-200 flex flex-col items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
